name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint backend code
      run: |
        cd backend
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test backend
      run: |
        cd backend
        # Add your test commands here when you have tests
        python -c "import main; print('Backend imports successfully')"

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint frontend code
      run: |
        cd frontend
        npm run lint || echo "No lint script found, skipping..."
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Test frontend
      run: |
        cd frontend
        # Add your test commands here when you have tests
        echo "Frontend tests would run here"

  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit for backend
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install safety
        pip install -r requirements.txt
        safety check || echo "Security check completed with warnings"
    
    - name: Run security audit for frontend
      run: |
        cd frontend
        npm audit --audit-level moderate || echo "Security audit completed with warnings"

  build-and-deploy:
    needs: [backend-tests, frontend-tests, security-check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build application
      run: |
        echo "Building application for deployment..."
        # Add your deployment build steps here
    
    - name: Deploy to staging
      run: |
        echo "Deployment steps would go here"
        # Add your deployment commands here
